//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется tvnviewer.rc
//
#define IDB_TOOLBAR                     101
#define IDI_CNOCURSOR                   102
#define IDI_CSMALLDOT                   103
#define IDI_APPICON                     104
#define IDI_FILE_ICON                   105
#define IDI_FILEUP                      106
#define IDI_ICON1                       107
#define IDI_FOLDER_ICON                 108
#define IDI_CDOT                        109
#define IDS_NEW_CONN                    120
#define IDD_ABOUT_DIALOG                121
#define ftclient_createFolderDialog     122
#define IDS_LISTENING_OPTIONS           122
#define ftclient_mainDialog             123
#define IDS_CONFIG                      123
#define ftclient_fileExistDialog        124
#define IDS_CLOSE                       124
#define IDS_URL_LICENSING_FVA           125
#define IDS_URL_PRODUCT_FVA             126
#define IDD_CMDLINE                     127
#define IDS_CMDLINE_HELP                127
#define IDS_FAILED_TO_OPEN_URL_FORMAT   128
#define IDD_CONFIGURATION               129
#define IDS_TB_TOOLBAR                  129
#define IDS_MBC_TVNVIEWER               130
#define IDD_DAUTH                       131
#define IDS_ERROR_IN_PROTOCOL           131
#define IDS_DISCONNECT                  132
#define IDS_PRODUCT_VERSION_FORMAT      133
#define IDD_LOGINDIALOG                 134
#define IDS_SAVE_SESSION_FILTER_VNC_FILES 134
#define IDS_SAVE_SESSION_FILTER_ALL_FILES 135
#define IDD_OPTIONS                     136
#define IDS_SECURITY_WARNING_CAPTION    136
#define IDR_ACCEL_APP_KEYS              137
#define IDS_LICENSING_INFO              137
#define IDS_QUESTION_SAVE_PASSWORD      138
#define IDB_LOGO_BIG                    139
#define IDS_CONNECTION_INFO_CAPTION     139
#define IDS_ABOUT_VIEWER                140
#define IDB_LOGO_48                     141
#define IDS_CONNECTION_INFO_FORMAT      141
#define IDS_URL_LICENSING_FVC           142
#define IDS_UNKNOWN_ERROR_IN_VIEWER     143
#define IDS_CONFIGURATION_LISTEN_PORT   144
#define IDS_CONFIGURATION_LOG_LEVEL     145
#define IDS_CONFIGURATION_HISTORY_LIMIT 146
#define IDS_OPTIONS_SCALE               147
#define IDS_CONFIGURATION_CAPTION       148
#define IDS_OPTIONS_CAPTION             149
#define IDS_ERROR_VALUE_FIELD_ONLY_NUMERIC 150
#define IDS_ERROR_VALUE_FIELD_ONLY_POSITIVE_NUMERIC 151
#define IDS_ERROR_START_LISTENING       152
#define IDS_ERROR_COMMAND_LINE          153
#define IDS_ERROR_PARSE_OPTIONS_FILE    154
#define IDS_TB_NEWCONNECTION            200
#define IDS_TB_SAVESESSION              201
#define IDS_TB_CONNOPTIONS              202
#define IDS_TB_CONNINFO                 203
#define IDS_TB_PAUSE                    204
#define IDS_TB_REFRESH                  205
#define IDS_TB_CTRLALTDEL               206
#define IDS_TB_CTRLESC                  207
#define IDS_TB_CTRL                     208
#define IDS_TB_ALT                      209
#define IDS_TB_TRANSFER                 210
#define IDS_TB_SCALEIN                  211
#define IDS_TB_SCALEOUT                 212
#define IDS_TB_SCALE100                 213
#define IDS_TB_SCALEAUTO                214
#define IDS_TB_FULLSCREEN               215
#define IDS_TB_CONFIGURATION            216
#define IDD_FS_WARNING                  230
#define IDD_DISPATCH_ID                 231
#define IDC_LABEL                       1001
#define IDC_FILENAME_EDIT               1002
#define IDC_FILENAME_LABEL              1004
#define IDC_SIZE1_LABEL                 1005
#define IDC_SIZE2_LABEL                 1006
#define IDC_DATE1_LABEL                 1007
#define IDC_DATE2_LABEL                 1008
#define IDC_OVERWRITE_BUTTON            1009
#define IDC_OVERWRITE_ALL_BUTTON        1010
#define IDC_SKIP_BUTTON                 1011
#define IDC_SKIP_ALL_BUTTON             1012
#define IDC_APPEND_BUTTON               1013
#define IDC_LOCAL_CURRENT_FOLDER_EDIT   1015
#define IDC_LOCAL_FILE_LIST             1016
#define IDC_RENAME_LOCAL_BUTTON         1017
#define IDC_MKDIR_LOCAL_BUTTON          1018
#define IDC_REMOVE_LOCAL_BUTTON         1019
#define IDC_REFRESH_LOCAL_BUTTON        1020
#define IDC_UPLOAD_BUTTON               1021
#define IDC_DOWNLOAD_BUTTON             1022
#define IDC_REMOTE_CURRENT_FOLDER_EDIT  1023
#define IDC_REMOTE_FILE_LIST            1024
#define IDC_RENAME_REMOTE_BUTTON        1025
#define IDC_MKDIR_REMOTE_BUTTON         1026
#define IDC_REMOVE_REMOTE_BUTTON        1027
#define IDC_REFRESH_REMOTE_BUTTON       1028
#define IDC_LOG_COMBO                   1029
#define IDC_TOTAL_PROGRESS              1030
#define IDC_CANCEL_BUTTON               1031
#define IDC_SHELP                       1032
#define IDC_CSHOWTOOLBARS               1033
#define IDC_CWARNATSW                   1034
#define IDC_BCLEAR_LIST                 1035
#define IDC_EREVCON                     1036
#define IDC_SREVCON                     1037
#define IDC_EVERBLVL                    1038
#define IDC_SVERBLVL                    1039
#define IDC_ELOGGING                    1040
#define IDC_ENUMCON                     1041
#define IDC_SNUMCON                     1042
#define IDC_EPASSW                      1043
#define IDC_EHOST                       1044
#define IDC_SSERVER                     1045
#define IDC_BOPTIONS                    1046
#define IDC_BCONFIGURATION              1047
#define IDC_CSERVER                     1048
#define IDC_CUSEENC                     1049
#define IDC_CEIGHTBIT                   1050
#define IDC_CCOMPRLVL                   1051
#define IDC_SCOMP                       1052
#define IDC_SQUALITY                    1053
#define IDC_SFAST                       1054
#define IDC_SBEST                       1055
#define IDC_CJPEG                       1056
#define IDC_SJPEG                       1057
#define IDC_SPOOR                       1058
#define IDC_SBEST2                      1059
#define IDC_CCOPYRECT                   1060
#define IDC_CSCALE                      1061
#define IDC_CFULLSCR                    1062
#define IDC_CDEICONFY                   1063
#define IDC_CEMUL3B                     1064
#define IDC_CSWAPMOUSE                  1065
#define IDC_RTRACK                      1066
#define IDC_RCURSOR                     1067
#define IDC_RNCURSOR                    1068
#define IDC_CSHAREDSES                  1069
#define IDC_CVIEWONLY                   1070
#define IDC_CDISCLIP                    1071
#define IDC_RDOT                        1072
#define IDC_RSMALLDOT                   1073
#define IDC_RARROW                      1074
#define IDC_RNLOCAL                     1075
#define IDC_SQUALITY2                   1076
#define IDC_STQUALITY                   1077
#define IDC_STQUALITY2                  1078
#define IDC_VISIT_WEB_SITE_BUTTON       1079
#define IDC_ORDER_SUPPORT_BUTTON        1080
#define IDC_STATIC_VERSION              1081
#define IDC_STATIC_LICENSING            1082
#define IDC_LISTENING                   1083
#define IDC_BABOUT                      1084
#define IDC_OPEN_LOG_FOLDER_BUTTON      1087
#define IDC_CWARN_FS                    1088
#define IDC_ID_EDIT                     1089
#define IDC_LABEL_ID                    1090
#define ID_CONN_OPTIONS                 40001
#define ID_CONN_INFO                    40002
#define ID_SHOW_TOOLBAR                 40004
#define ID_FULL_SCR                     40005
#define ID_REQ_SCR_REFRESH              40006
#define ID_CTRL_ALT_DEL                 40007
#define ID_TRANSF_FILES                 40008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        232
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
